"""LoRA supervised fine-tuning for CrashDiag's action policy.

Install the training extras before invoking this module.  Importing it is safe
without those dependencies; all heavyweight imports happen inside ``train``.

The JSONL generated by ``training.generate_dataset`` is a conversational
prompt-completion dataset.  ``completion_only_loss=True`` ensures observations
and system instructions are context, never SFT labels.
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .artifacts import (
    ArtifactError,
    add_artifact_arguments,
    make_checkpoint_upload_callback,
    preload_env,
    process_is_world_zero,
    uploader_from_args,
)
from .common import PRECISION_CHOICES, resolve_precision
from .reporting import ReportBundle, generate_trainer_report


DEFAULT_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
DEFAULT_DATASET = Path("data/sft_train.jsonl")
DEFAULT_EVAL_DATASET = Path("data/sft_eval.jsonl")
DEFAULT_OUTPUT = Path("outputs/sft")


def _positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def _non_negative_float(value: str) -> float:
    parsed = float(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return parsed


def _target_modules(value: str) -> str | list[str]:
    value = value.strip()
    if not value:
        raise argparse.ArgumentTypeError("target modules cannot be empty")
    if value == "all-linear":
        return value
    modules = [item.strip() for item in value.split(",") if item.strip()]
    if not modules:
        raise argparse.ArgumentTypeError("target modules cannot be empty")
    return modules


def _split_dataset(dataset: Any, eval_ratio: float, seed: int) -> tuple[Any, Any | None]:
    """Make a deterministic per-fault eval split without requiring ClassLabel."""

    if eval_ratio <= 0 or len(dataset) < 2:
        return dataset, None
    if eval_ratio >= 1:
        raise ValueError("eval_ratio must be less than 1")
    if "fault_name" not in dataset.column_names:
        split = dataset.train_test_split(test_size=eval_ratio, seed=seed)
        return split["train"], split["test"]

    import random

    groups: dict[str, list[int]] = {}
    for index, name in enumerate(dataset["fault_name"]):
        groups.setdefault(str(name), []).append(index)
    rng = random.Random(seed)
    eval_indices: list[int] = []
    for name in sorted(groups):
        indices = groups[name][:]
        if len(indices) < 2:
            continue
        rng.shuffle(indices)
        count = max(1, round(len(indices) * eval_ratio))
        count = min(count, len(indices) - 1)
        eval_indices.extend(indices[:count])
    if not eval_indices:
        return dataset, None
    eval_set = set(eval_indices)
    train_indices = [index for index in range(len(dataset)) if index not in eval_set]
    return dataset.select(train_indices), dataset.select(sorted(eval_indices))


def train(args: argparse.Namespace) -> Any:
    """Run SFT and return TRL's training result."""

    try:
        import torch
        from datasets import load_dataset
        from peft import LoraConfig, TaskType
        from transformers import AutoTokenizer
        from trl import SFTConfig, SFTTrainer
    except ImportError as exc:
        raise SystemExit(
            "SFT dependencies are missing. Install them with "
            "`pip install -e .[train]`."
        ) from exc

    if not args.dataset.is_file():
        raise SystemExit(
            f"SFT dataset not found: {args.dataset}. Run "
            "`python -m training.generate_dataset` first."
        )
    if args.eval_dataset is not None and not args.eval_dataset.is_file():
        raise SystemExit(f"evaluation dataset not found: {args.eval_dataset}")

    bf16, fp16 = resolve_precision(torch, args.precision)
    if bf16:
        model_dtype = torch.bfloat16
    elif fp16:
        model_dtype = torch.float16
    else:
        model_dtype = torch.float32

    train_dataset = load_dataset("json", data_files=str(args.dataset), split="train")
    if args.eval_dataset is not None:
        eval_dataset = load_dataset(
            "json", data_files=str(args.eval_dataset), split="train"
        )
    else:
        train_dataset, eval_dataset = _split_dataset(
            train_dataset, args.eval_ratio, args.seed
        )

    tokenizer_source = args.tokenizer or args.model
    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_source,
        trust_remote_code=args.trust_remote_code,
    )
    if tokenizer.pad_token_id is None:
        if tokenizer.eos_token_id is None:
            raise SystemExit("tokenizer has neither a pad token nor an EOS token")
        tokenizer.pad_token = tokenizer.eos_token

    eval_enabled = eval_dataset is not None and len(eval_dataset) > 0
    uploader = getattr(args, "artifact_uploader", None)
    callback = make_checkpoint_upload_callback(uploader, "sft")
    config = SFTConfig(
        output_dir=str(args.output_dir),
        num_train_epochs=args.epochs,
        learning_rate=args.learning_rate,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.eval_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        warmup_ratio=args.warmup_ratio,
        logging_steps=args.logging_steps,
        save_strategy=args.save_strategy,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        eval_strategy="epoch" if eval_enabled else "no",
        seed=args.seed,
        data_seed=args.seed,
        max_length=args.max_length,
        completion_only_loss=True,
        packing=args.packing,
        gradient_checkpointing=args.gradient_checkpointing,
        bf16=bf16,
        fp16=fp16,
        report_to=args.report_to,
        trust_remote_code=args.trust_remote_code,
        model_init_kwargs={"dtype": model_dtype},
    )
    lora = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=args.lora_target_modules,
        bias="none",
    )
    trainer = SFTTrainer(
        model=args.model,
        args=config,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset if eval_enabled else None,
        processing_class=tokenizer,
        peft_config=lora,
        callbacks=[callback] if callback is not None else None,
    )
    result = trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
    trainer.save_model(str(args.output_dir))
    eval_metrics = trainer.evaluate() if eval_enabled else None
    report_bundle: ReportBundle | None = None
    if trainer.is_world_process_zero():
        tokenizer.save_pretrained(str(args.output_dir))
        trainer.save_state()
        trainer.log_metrics("train", result.metrics)
        trainer.save_metrics("train", result.metrics)
        if eval_metrics is not None:
            trainer.log_metrics("eval", eval_metrics)
            trainer.save_metrics("eval", eval_metrics)
        report_bundle = generate_trainer_report(
            args.output_dir / "trainer_state.json",
            args.output_dir / "reports",
            kind="sft",
            title="CrashDiag SFT training metrics",
        )
        print(f"SFT report: {report_bundle.summary_path}")
    trainer.accelerator.wait_for_everyone()
    if trainer.is_world_process_zero() and uploader is not None:
        uploader.upload_directory(
            args.output_dir,
            "sft",
            metadata={
                "model": args.model,
                "train_metrics": result.metrics,
                "eval_metrics": eval_metrics,
                "report": report_bundle.summary if report_bundle is not None else None,
            },
        )
    trainer.accelerator.wait_for_everyone()
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="LoRA SFT on mechanically validated CrashDiag actions.",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--tokenizer", default=None)
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--eval-dataset", type=Path, default=DEFAULT_EVAL_DATASET)
    parser.add_argument(
        "--no-eval-dataset",
        action="store_const",
        const=None,
        dest="eval_dataset",
        help="split --dataset using --eval-ratio instead of loading a separate file",
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--epochs", type=float, default=3.0)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--batch-size", type=_positive_int, default=2)
    parser.add_argument("--eval-batch-size", type=_positive_int, default=2)
    parser.add_argument("--gradient-accumulation-steps", type=_positive_int, default=8)
    parser.add_argument("--max-length", type=_positive_int, default=2048)
    parser.add_argument("--warmup-ratio", type=_non_negative_float, default=0.03)
    parser.add_argument("--eval-ratio", type=_non_negative_float, default=0.1)
    parser.add_argument("--logging-steps", type=_positive_int, default=10)
    parser.add_argument(
        "--save-strategy", choices=("epoch", "steps"), default="epoch"
    )
    parser.add_argument("--save-steps", type=_positive_int, default=50)
    parser.add_argument("--save-total-limit", type=_positive_int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--precision", choices=PRECISION_CHOICES, default="auto")
    parser.add_argument("--lora-rank", type=_positive_int, default=16)
    parser.add_argument("--lora-alpha", type=_positive_int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument(
        "--lora-target-modules",
        type=_target_modules,
        default="all-linear",
        help="all-linear or a comma-separated module suffix list",
    )
    parser.add_argument("--packing", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument(
        "--gradient-checkpointing",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--trust-remote-code", action="store_true")
    parser.add_argument("--report-to", default="none")
    parser.add_argument("--resume-from-checkpoint", default=None)
    add_artifact_arguments(parser)
    return parser


def _validate_args(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    if args.epochs <= 0:
        parser.error("--epochs must be positive")
    if args.learning_rate <= 0:
        parser.error("--learning-rate must be positive")
    if not 0 <= args.eval_ratio < 1:
        parser.error("--eval-ratio must be at least 0 and less than 1")
    if not 0 <= args.warmup_ratio <= 1:
        parser.error("--warmup-ratio must be between 0 and 1")
    if not 0 <= args.lora_dropout < 1:
        parser.error("--lora-dropout must be at least 0 and less than 1")


def main(argv: Sequence[str] | None = None) -> int:
    preload_env(argv)
    parser = build_parser()
    args = parser.parse_args(argv)
    _validate_args(parser, args)
    try:
        uploader = uploader_from_args(args)
        args.artifact_uploader = uploader
        if uploader is not None and process_is_world_zero():
            uploader.start_stage(
                "sft",
                {
                    "model": args.model,
                    "dataset": str(args.dataset),
                    "output_dir": str(args.output_dir),
                },
            )
        train(args)
    except ArtifactError as exc:
        parser.exit(2, f"SFT artifact error: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
